# Generated by Django 3.2.4 on 2021-07-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=512)),
                ('date_created', models.DateField()),
                ('last_login', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512, null=True)),
                ('uuid', models.UUIDField()),
                ('date_created', models.DateField()),
                ('last_modified', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=512)),
                ('term_image', models.FileField(blank=True, null=True, upload_to='')),
                ('definition', models.CharField(max_length=512)),
                ('definition_image', models.FileField(blank=True, null=True, upload_to='')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.deck')),
            ],
        ),
    ]
