# Generated by Django 3.2.4 on 2021-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210714_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='definition_image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Zeusz\\Django\\quizcards\\static\\media'),
        ),
        migrations.AlterField(
            model_name='card',
            name='term_image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Zeusz\\Django\\quizcards\\static\\media'),
        ),
    ]
