# Generated by Django 3.2.4 on 2021-06-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
