# Generated by Django 3.2.4 on 2021-08-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210725_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
