# Generated by Django 3.2.4 on 2021-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='creator',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
    ]
