# Generated by Django 3.2.4 on 2021-07-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210629_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
