# Generated by Django 3.2.4 on 2021-07-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210701_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(),
        ),
    ]
